DBCSAN_CLUSTRING

In [1]:
#Import the libraries
from sklearn.cluster import DBSCAN
from sklearn.preprocessing import StandardScaler
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
data3= pd.read_csv("C:/Users/abc/Desktop/Assignments/Assignment 7/crime_data.csv")
data3.head()

   Unnamed: 0  Murder  Assault  UrbanPop  Rape
0     Alabama    13.2      236        58  21.2
1      Alaska    10.0      263        48  44.5
2     Arizona     8.1      294        80  31.0
3    Arkansas     8.8      190        50  19.5
4  California     9.0      276        91  40.6

In [6]:
data3.shape

(50, 5)

In [7]:
data3.drop(['Unnamed: 0'],axis=1,inplace=True)

In [8]:
array=data3.values

In [9]:
stscaler = StandardScaler().fit(array)
X = stscaler.transform(array)

In [16]:
#min sample is equal to totao feacture +1
dbscan = DBSCAN(eps=1.3, min_samples=5)
dbscan.fit(X)

DBSCAN(eps=1.3)

In [17]:
#Noisy samples are given the label -1.
dbscan.labels_

array([ 0, -1,  0,  0, -1,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
      dtype=int64)

In [18]:
cl=pd.DataFrame(dbscan.labels_,columns=['cluster'])

In [19]:
pd.concat([data3,cl],axis=1)

    Murder  Assault  UrbanPop  Rape  cluster
0     13.2      236        58  21.2        0
1     10.0      263        48  44.5       -1
2      8.1      294        80  31.0        0
3      8.8      190        50  19.5        0
4      9.0      276        91  40.6       -1
5      7.9      204        78  38.7        0
6      3.3      110        77  11.1        0
7      5.9      238        72  15.8        0
8     15.4      335        80  31.9       -1
9     17.4      211        60  25.8        0
10     5.3       46        83  20.2        0
11     2.6      120        54  14.2        0
12    10.4      249        83  24.0        0
13     7.2      113        65  21.0        0
14     2.2       56        57  11.3        0
15     6.0      115        66  18.0        0
16     9.7      109        52  16.3        0
17    15.4      249        66  22.2        0
18     2.1       83        51   7.8        0
19    11.3      300        67  27.8        0
20     4.4      149        85  16.3        0
21    12.1      255        74  35.1        0
22     2.7       72        66  14.9        0
23    16.1      259        44  17.1        0
24     9.0      178        70  28.2        0
25     6.0      109        53  16.4        0
26     4.3      102        62  16.5        0
27    12.2      252        81  46.0        0
28     2.1       57        56   9.5        0
29     7.4      159        89  18.8        0
30    11.4      285        70  32.1        0
31    11.1      254        86  26.1        0
32    13.0      337        45  16.1       -1
33     0.8       45        44   7.3        0
34     7.3      120        75  21.4        0
35     6.6      151        68  20.0        0
36     4.9      159        67  29.3        0
37     6.3      106        72  14.9        0
38     3.4      174        87   8.3        0
39    14.4      279        48  22.5        0
40     3.8       86        45  12.8        0
41    13.2      188        59  26.9        0
42    12.7      201        80  25.5        0
43     3.2      120        80  22.9        0
44     2.2       48        32  11.2        0
45     8.5      156        63  20.7        0
46     4.0      145        73  26.2        0
47     5.7       81        39   9.3        0
48     2.6       53        66  10.8        0
49     6.8      161        60  15.6        0